name: Purge jsDelivr Cache for every css in root folder

on:
  push:
    branches:
      - main

jobs:
  purge-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get CSS files
        id: cssfiles
        run: |
          echo "::set-output name=files::$(find . -name '*.css' -exec basename {} \;)"

      - name: Send purge request to jsDelivr
        run: |
          for file in ${{ steps.cssfiles.outputs.files }}
          do
            echo "Purging: $file"
            curl -X GET "https://purge.jsdelivr.net/gh/maxipizzasa/GoOrder@main/${file}"
          done